source 'https://rubygems.org'

gem 'rails', '>= 5.0', '< 5.1'
gem 'pg', '~> 0.18'
gem 'puma'
gem 'devise', '4.1.0'
gem 'factory_girl_rails', '4.7.0'
gem 'faker', '1.6.3'
gem 'jwt', '1.5.4'
gem 'active_model_serializers', '0.9.5'
gem 'paranoia', github: 'rubysherpas/paranoia', branch: 'release-3.0.0'
gem 'wupee', '1.1.4'

group :development, :test do
  gem 'rspec-rails', '3.5.0.beta1'
  gem 'byebug'
end

group :development do
  gem 'rack-cors', '0.4.0'
  gem 'web-console', '~> 3.0'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'guard-rspec',  github: 'guard/guard-rspec', branch: 'rails-5-support'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
